baseURL = 'http://lxizaxi.github.io/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'lxizaxi'
theme = 'PaperMod'

[author]
  name = "lxizaxi"
  bio = "just developer."
  job = "engineer"
  location = "Nagoya"

[params.profileMode]
enabled = true
title = "Welcome to shota.suzuki's home page"
subtitle = 'Always Under Construction.'
imageUrl =  "icon2.jpg"

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  dateFormat = "2006-01-02"
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  coverImage = "images/cover.jpg"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  socialIcons = [
    { name = 'github', title = 'github', url = 'https://github.com/lxizaxi/' },
    { name = 'twitter', title = 'twitter', url = 'https://twitter.com/lxizaxi'}
  ]

[[menu.main]]
  weight = 1
  identifier = "tech"
  name = "Tech"
  url = "/tech"
[[menu.main]]
  weight = 2
  identifier = "blog"
  name = "Blog"
  url = "/blog"
[[menu.main]]
  weight = 3
  identifier = "aboutme"
  name = "About Me"
  url = "/aboutme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true