baseURL = 'http://tanegcp.github.io/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'tanegcp'
theme = 'PaperMod'

[author]
  name = "tanegcp"
  bio = "just developer."
  job = "engineer"
  location = "Nagoya"

[params.profileMode]
enabled = true
title = "tanegcpのスペース"
subtitle = '学びや気づきを整理します'
imageUrl =  "icon.jpg"

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  dateFormat = "2006-01-02"
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  coverImage = "images/cover.jpg"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  socialIcons = [
    { name = 'github', title = 'github', url = 'https://github.com/tanegcp/' },
    { name = 'twitter', title = 'twitter', url = 'https://twitter.com/tanegcp'}
  ]

[[menu.main]]
  weight = 1
  identifier = "blog"
  name = "Blog"
  url = "/blog"
[[menu.main]]
  weight = 2
  identifier = "aboutme"
  name = "About Me"
  url = "/aboutme"
